"""
This type stub file was generated by pyright.
"""

import dspy
from typing import List, Optional, Union
from dspy.experimental.synthesizer.config import SynthesizerArguments

class Synthesizer:
    def __init__(self, config: SynthesizerArguments) -> None: ...
    def generate(
        self,
        ground_source: Union[List[dspy.Example], dspy.Signature],
        num_data: int,
        batch_size: int = ...,
    ):  # -> list[Any]:
        ...
    def export(
        self, data: List[dspy.Example], path: str, mode: Optional[str] = ..., **kwargs
    ):  # -> None:
        ...
