"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional

class Embeddings:
    def __init__(self, corpus: List[str], embedder, k: int = ..., callbacks: Optional[List[Any]] = ..., cache: bool = ..., brute_force_threshold: int = ..., normalize: bool = ...) -> None:
        ...
    
    def __call__(self, query: str): # -> Prediction:
        ...
    
    def forward(self, query: str): # -> Prediction:
        ...
    


