"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Union
from dspy.predict.parameter import Parameter
from dspy.primitives.prediction import Prediction
from dspy.utils.callback import with_callbacks

def single_query_passage(passages): # -> Prediction:
    ...

class Retrieve(Parameter):
    name = ...
    input_variable = ...
    desc = ...
    def __init__(self, k=..., callbacks=...) -> None:
        ...
    
    def reset(self): # -> None:
        ...
    
    def dump_state(self): # -> dict[str, Any]:
        ...
    
    def load_state(self, state): # -> None:
        ...
    
    @with_callbacks
    def __call__(self, *args, **kwargs): # -> List[str] | Prediction | List[Prediction]:
        ...
    
    def forward(self, query: str, k: Optional[int] = ..., **kwargs) -> Union[List[str], Prediction, List[Prediction]]:
        ...
    


