"""
This type stub file was generated by pyright.
"""

def EM(prediction, answers_list): # -> bool:
    ...

def F1(prediction, answers_list): # -> float | int:
    ...

def HotPotF1(prediction, answers_list): # -> float | int:
    ...

def normalize_text(s): # -> str:
    ...

def em_score(prediction, ground_truth): # -> bool:
    ...

def f1_score(prediction, ground_truth): # -> float | Literal[0]:
    ...

def hotpot_f1_score(prediction, ground_truth): # -> float | Literal[0]:
    ...

def precision_score(prediction, ground_truth): # -> float | Literal[0]:
    ...

def answer_exact_match(example, pred, trace=..., frac=...): # -> bool:
    ...

def answer_passage_match(example, pred, trace=...): # -> bool:
    ...

