"""
This type stub file was generated by pyright.
"""

def answer_exact_match(example, pred, trace=..., frac=...):  # -> bool:
    ...
def answer_passage_match(example, pred, trace=...):  # -> bool:
    ...
