"""
This type stub file was generated by pyright.
"""

from abc import ABC, abstractmethod

class Proposer(ABC):
    def __init__(self) -> None:
        ...
    
    @abstractmethod
    def propose_instructions_for_program(self): # -> None:
        ...
    
    def propose_instruction_for_predictor(self): # -> None:
        ...
    


