"""
This type stub file was generated by pyright.
"""

def strip_prefix(text): # -> str:
    ...

def create_instruction_set_history_string(base_program, trial_logs, top_n): # -> str:
    ...

def parse_list_of_instructions(instruction_string): # -> Any | list[Any]:
    ...

def get_program_instruction_set_string(program): # -> LiteralString:
    ...

def create_predictor_level_history_string(base_program, predictor_i, trial_logs, top_n): # -> Literal['']:
    ...

def create_example_string(fields, example): # -> LiteralString:
    ...

def get_dspy_source_code(module): # -> str:
    ...

