"""
This type stub file was generated by pyright.
"""

from typing import Literal
from pydantic.fields import FieldInfo

def get_dspy_field_type(field: FieldInfo) -> Literal["input", "output"]:
    ...

