"""
This type stub file was generated by pyright.
"""

import os
import requests
from dspy.streaming.messages import StatusMessage, StatusMessageProvider
from dspy.utils import exceptions
from dspy.utils.callback import BaseCallback, with_callbacks
from dspy.utils.dummies import DummyLM, DummyVectorizer, dummy_rm
from dspy.utils.inspect_history import pretty_print_history

def download(url): # -> None:
    ...

__all__ = ["download", "exceptions", "BaseCallback", "with_callbacks", "DummyLM", "DummyVectorizer", "dummy_rm", "StatusMessage", "StatusMessageProvider", "pretty_print_history"]
