"""
This type stub file was generated by pyright.
"""

_DEFAULT_CACHE_DIR = ...
DSPY_CACHEDIR = ...

def create_subdir_in_cachedir(subdir: str) -> str:
    """Create a subdirectory in the DSPy cache directory."""
    ...
