"""
This type stub file was generated by pyright.
"""

from typing import Optional
from dspy.signatures.signature import Signature

class AdapterParseError(Exception):
    """Exception raised when adapter cannot parse the LM response."""
    def __init__(
        self,
        adapter_name: str,
        signature: Signature,
        lm_response: str,
        message: Optional[str] = ...,
        parsed_result: Optional[str] = ...,
    ) -> None: ...
