"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from dspy.adapters.types.tool import Tool
from langchain.tools import BaseTool

if TYPE_CHECKING: ...

def convert_langchain_tool(tool: BaseTool) -> Tool:
    """Build a DSPy tool from a LangChain tool.

    This function converts a LangChain tool (either created with @tool decorator
    or by subclassing BaseTool) into a DSPy Tool.

    Args:
        tool: The LangChain tool to convert.

    Returns:
        A DSPy Tool object.
    """
    ...
