"""
This type stub file was generated by pyright.
"""

LOGGING_LINE_FORMAT = ...
LOGGING_DATETIME_FORMAT = ...
class DSPyLoggingStream:
    """
    A Python stream for use with event logging APIs throughout DSPy (`eprint()`,
    `logger.info()`, etc.). This stream wraps `sys.stderr`, forwarding `write()` and
    `flush()` calls to the stream referred to by `sys.stderr` at the time of the call.
    It also provides capabilities for disabling the stream to silence event logs.
    """
    def __init__(self) -> None:
        ...
    
    def write(self, text): # -> None:
        ...
    
    def flush(self): # -> None:
        ...
    
    @property
    def enabled(self): # -> bool:
        ...
    
    @enabled.setter
    def enabled(self, value): # -> None:
        ...
    


DSPY_LOGGING_STREAM = ...
def disable_logging(): # -> None:
    """
    Disables the `DSPyLoggingStream` used by event logging APIs throughout DSPy
    (`eprint()`, `logger.info()`, etc), silencing all subsequent event logs.
    """
    ...

def enable_logging(): # -> None:
    """
    Enables the `DSPyLoggingStream` used by event logging APIs throughout DSPy
    (`eprint()`, `logger.info()`, etc), emitting all subsequent event logs. This
    reverses the effects of `disable_logging()`.
    """
    ...

def configure_dspy_loggers(root_module_name): # -> None:
    ...

