"""
This type stub file was generated by pyright.
"""

import mcp
from typing import TYPE_CHECKING
from dspy.adapters.types.tool import Tool

if TYPE_CHECKING: ...

def convert_mcp_tool(session: mcp.client.session.ClientSession, tool: mcp.types.Tool) -> Tool:
    """Build a DSPy tool from an MCP tool.

    Args:
        session: The MCP session to use.
        tool: The MCP tool to convert.

    Returns:
        A dspy Tool object.
    """
    ...
