"""
This type stub file was generated by pyright.
"""

logger = ...

class ParallelExecutor:
    def __init__(
        self,
        num_threads=...,
        max_errors=...,
        disable_progress_bar=...,
        provide_traceback=...,
        compare_results=...,
        timeout=...,
        straggler_limit=...,
    ) -> None:
        """
        Offers isolation between the tasks (dspy.settings) irrespective of whether num_threads == 1 or > 1.
        Handles also straggler timeouts.
        """
        ...

    def execute(self, function, data):  # -> list[None]:
        ...
