"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from dspy.primitives.module import Module

if TYPE_CHECKING:
    ...
logger = ...
def get_dependency_versions(): # -> dict[str, str]:
    ...

def load(path: str) -> Module:
    """Load saved DSPy model.

    This method is used to load a saved DSPy model with `save_program=True`, i.e., the model is saved with cloudpickle.

    Args:
        path (str): Path to the saved model.

    Returns:
        The loaded model, a `dspy.Module` instance.
    """
    ...

