"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from typing import Any

"""Usage tracking utilities for DSPy."""

class UsageTracker:
    """Tracks LM usage data within a context."""
    def __init__(self) -> None: ...
    def add_usage(self, lm: str, usage_entry: dict):  # -> None:
        """Add a usage entry to the tracker."""
        ...

    def get_total_tokens(self) -> dict[str, dict[str, Any]]:
        """Calculate total tokens from all tracked usage."""
        ...

@contextmanager
def track_usage():  # -> Generator[UsageTracker, Any, None]:
    """Context manager for tracking LM usage."""
    ...
