"""
This type stub file was generated by pyright.
"""

from typing import Callable, List, Optional
from dspy.primitives.example import Example
from dspy.primitives.module import Module
from dspy.teleprompt.teleprompt import Teleprompter

logger = ...
class BetterTogether(Teleprompter):
    STRAT_SEP = ...
    def __init__(self, metric: Callable, prompt_optimizer: Optional[Teleprompter] = ..., weight_optimizer: Optional[Teleprompter] = ..., seed: Optional[int] = ...) -> None:
        ...
    
    def compile(self, student: Module, trainset: List[Example], strategy: str = ..., valset_ratio=...) -> Module:
        ...
    


