"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional
from dspy.teleprompt.teleprompt import Teleprompter

logger = ...

class BootstrapFewShot(Teleprompter):
    def __init__(
        self,
        metric=...,
        metric_threshold=...,
        teacher_settings: Optional[Dict] = ...,
        max_bootstrapped_demos=...,
        max_labeled_demos=...,
        max_rounds=...,
        max_errors=...,
    ) -> None:
        """A Teleprompter class that composes a set of demos/examples to go into a predictor's prompt.
        These demos come from a combination of labeled examples in the training set, and bootstrapped demos.

        Args:
            metric (Callable): A function that compares an expected value and predicted value,
                outputting the result of that comparison.
            metric_threshold (float, optional): If the metric yields a numerical value, then check it
                against this threshold when deciding whether or not to accept a bootstrap example.
                Defaults to None.
            teacher_settings (dict, optional): Settings for the `teacher` model.
                Defaults to None.
            max_bootstrapped_demos (int): Maximum number of bootstrapped demonstrations to include.
                Defaults to 4.
            max_labeled_demos (int): Maximum number of labeled demonstrations to include.
                Defaults to 16.
            max_rounds (int): Number of iterations to attempt generating the required bootstrap
                examples. If unsuccessful after `max_rounds`, the program ends. Defaults to 1.
            max_errors (int): Maximum number of errors until program ends. Defaults to 5.
        """
        ...

    def compile(self, student, *, teacher=..., trainset): ...
