"""
This type stub file was generated by pyright.
"""

from dspy.teleprompt.teleprompt import Teleprompter

class Ensemble(Teleprompter):
    def __init__(self, *, reduce_fn=..., size=..., deterministic=...) -> None:
        """A common reduce_fn is dspy.majority."""
        ...

    def compile(self, programs):  # -> EnsembledProgram:
        class EnsembledProgram(dspy.Module): ...
