"""
This type stub file was generated by pyright.
"""

from dspy.teleprompt.teleprompt import Teleprompter

class BootstrapFewShotWithRandomSearch(Teleprompter):
    def __init__(self, metric, teacher_settings=..., max_bootstrapped_demos=..., max_labeled_demos=..., max_rounds=..., num_candidate_programs=..., num_threads=..., max_errors=..., stop_at_score=..., metric_threshold=...) -> None:
        ...
    
    def compile(self, student, *, teacher=..., trainset, valset=..., restrict=..., labeled_sample=...):
        ...
    


