"""
This type stub file was generated by pyright.
"""

from .copro_optimizer import COPRO

class SignatureOptimizer(COPRO):
    def __init__(
        self,
        prompt_model=...,
        metric=...,
        breadth=...,
        depth=...,
        init_temperature=...,
        verbose=...,
        track_stats=...,
    ) -> None: ...
    def compile(self, student, *, devset, eval_kwargs): ...
