"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from dspy.primitives import Example, Module

class Teleprompter:
    def __init__(self) -> None:
        ...
    
    def compile(self, student: Module, *, trainset: list[Example], teacher: Optional[Module] = ..., valset: Optional[list[Example]] = ..., **kwargs) -> Module:
        """
        Optimize the student program.

        Args:
            student: The student program to optimize.
            trainset: The training set to use for optimization.
            teacher: The teacher program to use for optimization.
            valset: The validation set to use for optimization.

        Returns:
            The optimized student program.
        """
        ...
    
    def get_params(self) -> dict[str, Any]:
        """
        Get the parameters of the teleprompter.

        Returns:
            The parameters of the teleprompter.
        """
        ...
    


