"""
This type stub file was generated by pyright.
"""

from dspy.teleprompt.teleprompt import Teleprompter

class BootstrapFewShotWithOptuna(Teleprompter):
    def __init__(self, metric, teacher_settings=..., max_bootstrapped_demos=..., max_labeled_demos=..., max_rounds=..., num_candidate_programs=..., num_threads=...) -> None:
        ...
    
    def objective(self, trial):
        ...
    
    def compile(self, student, *, teacher=..., max_demos, trainset, valset=...): # -> Any:
        ...
    


