"""
This type stub file was generated by pyright.
"""

from dspy.teleprompt.teleprompt import Teleprompter

class LabeledFewShot(Teleprompter):
    def __init__(self, k=...) -> None: ...
    def compile(self, student, *, trainset, sample=...): ...
