"""
This type stub file was generated by pyright.
"""

import dspy

def get_number_with_suffix(number: int) -> str:
    ...

class Avatar(dspy.Module):
    def __init__(self, signature, tools, max_iters=..., verbose=...) -> None:
        ...
    
    def forward(self, **kwargs): # -> Prediction:
        ...
    


