"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional
from pydantic import BaseModel

class Tool(BaseModel):
    tool: Any
    name: str
    desc: Optional[str]
    input_type: Optional[str] = ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class Action(BaseModel):
    tool_name: Any = ...
    tool_input_query: Any = ...

class ActionOutput(BaseModel):
    tool_name: str
    tool_input_query: str
    tool_output: str
    ...
