"""
This type stub file was generated by pyright.
"""

import dspy.retrievers
from dspy.predict import *
from dspy.primitives import *
from dspy.retrieve import *
from dspy.signatures import *
from dspy.teleprompt import *
from dspy.evaluate import Evaluate
from dspy.clients import *
from dspy.clients import DSPY_CACHE
from dspy.adapters import (
    Adapter,
    Audio,
    BaseType,
    ChatAdapter,
    History,
    Image,
    JSONAdapter,
    Tool,
    ToolCalls,
    TwoStepAdapter,
)
from dspy.utils.logging_utils import configure_dspy_loggers, disable_logging, enable_logging
from dspy.utils.asyncify import asyncify
from dspy.utils.saving import load
from dspy.streaming.streamify import streamify
from dspy.utils.usage_tracker import track_usage
from dspy.dsp.utils.settings import settings
from dspy.dsp.colbertv2 import ColBERTv2
from .__metadata__ import (
    __author__,
    __author_email__,
    __description__,
    __name__,
    __url__,
    __version__,
)

configure = ...
context = ...
BootstrapRS = BootstrapFewShotWithRandomSearch
cache = ...
