"""
This type stub file was generated by pyright.
"""

import dspy
from typing import List, Union
from pyepsilla import vectordb

class EpsillaRM(dspy.Retrieve):
    def __init__(
        self,
        epsilla_client: vectordb.Client,
        db_name: str,
        db_path: str,
        table_name: str,
        k: int = ...,
        page_content: str = ...,
    ) -> None: ...
    def forward(
        self, query_or_queries: Union[str, List[str]], k: Union[int, None] = ..., **kwargs
    ) -> dspy.Prediction: ...
