"""
This type stub file was generated by pyright.
"""

import backoff
from typing import Any, List
from openai import APITimeoutError, InternalServerError, RateLimitError, UnprocessableEntityError
from dspy.dsp.utils.settings import settings
from dspy import Prediction, Retrieve

def build_vector_search_pipeline(
    index_name: str, query_vector: List[float], num_candidates: int, limit: int
) -> List[dict[str, Any]]: ...

class Embedder:
    def __init__(self, provider: str, model: str) -> None: ...
    @backoff.on_exception(
        backoff.expo,
        (APITimeoutError, InternalServerError, RateLimitError, UnprocessableEntityError),
        max_time=settings.backoff_time,
    )
    def __call__(self, queries) -> Any: ...

class MongoDBAtlasRM(Retrieve):
    def __init__(
        self,
        db_name: str,
        collection_name: str,
        index_name: str,
        k: int = ...,
        embedding_provider: str = ...,
        embedding_model: str = ...,
    ) -> None: ...
    def forward(self, query_or_queries: str) -> Prediction: ...
