"""
This type stub file was generated by pyright.
"""

import dspy
from typing import Optional, Union

class WatsonDiscoveryRM(dspy.Retrieve):
    """A retrieval module that uses Watson Discovery to return the top passages for a given query.

    Args:
        apikey (str): apikey for authentication purposes,
        url (str): endpoint URL that includes the service instance ID
        version (str): Release date of the version of the API you want to use. Specify dates in YYYY-MM-DD format.
        project_id (str): The Universally Unique Identifier (UUID) of the project.
        collection_ids (list): An array containing the collections on which the search will be executed.
        k (int, optional): The number of top passages to retrieve. Defaults to 5.

    Returns:
        dspy.Prediction: An object containing the retrieved passages.
    """
    def __init__(
        self,
        apikey: str,
        url: str,
        version: str,
        project_id: str,
        collection_ids: list = ...,
        k: int = ...,
    ) -> None: ...
    def forward(
        self, query_or_queries: Union[str, list[str]], k: Optional[int] = ...
    ) -> dspy.Prediction:
        """Search with Watson Discovery for self.k top passages for query.

        Args:
            query_or_queries (Union[str, List[str]]): The query or queries to search for.
            k (int, optional): The number of top passages to retrieve.

        Returns:
            dspy.Prediction: An object containing the retrieved passages.
        """
        ...
