"""
This type stub file was generated by pyright.
"""

import dspy
from typing import Literal, Optional, Union

class YouRM(dspy.Retrieve):
    """Retriever for You.com's Search and News API.

    [API reference](https://documentation.you.com/api-reference/)

    Args:
        ydc_api_key: you.com API key, if `YDC_API_KEY` is not set in the environment
        k: If ``endpoint="search"``, the max snippets to return per search hit.
           If ``endpoint="news"``, the max articles to return.
        endpoint: you.com endpoints
        num_web_results: The max number of web results to return, must be under 20
        safesearch: Safesearch settings, one of "off", "moderate", "strict", defaults to moderate
        country: Country code, ex: 'US' for United States, see API reference for more info
        search_lang: (News API) Language codes, ex: 'en' for English, see API reference for more info
        ui_lang: (News API) User interface language for the response, ex: 'en' for English.
                            See API reference for more info
        spellcheck: (News API) Whether to spell check query or not, defaults to True
    """
    def __init__(
        self,
        ydc_api_key: Optional[str] = ...,
        k: int = ...,
        endpoint: Literal["search", "news"] = ...,
        num_web_results: Optional[int] = ...,
        safesearch: Optional[Literal["off", "moderate", "strict"]] = ...,
        country: Optional[str] = ...,
        search_lang: Optional[str] = ...,
        ui_lang: Optional[str] = ...,
        spellcheck: Optional[bool] = ...,
    ) -> None: ...
    def forward(
        self, query_or_queries: Union[str, list[str]], k: Optional[int] = ...
    ) -> dspy.Prediction: ...
