"""
This type stub file was generated by pyright.
"""

graphviz_available = ...

class ModuleGraph:
    def __init__(self, module_name, module) -> None: ...
    def inspect_settings(self, settings):  # -> None:
        """Check for the existence and configuration of LM and RM and add them to the graph."""
        ...

    def add_module(self, module_name, module):  # -> None:
        """Add a module to the graph"""
        ...

    def generate_module_name(self, base_name, module_type):
        """Generate a module name based on the module type"""
        ...

    def process_submodules(self, module_name, module):  # -> None:
        """Process submodules of a module and add them to the graph"""
        ...

    def process_submodule(self, sub_module_name, sub_module):  # -> None:
        """Process a submodule and add it to the graph"""
        ...

    def render_graph(self, filename=...):  # -> None:
        """Render the graph to a file(png)"""
        ...
