"""
This type stub file was generated by pyright.
"""

import dspy
from typing import List, Optional
from pydantic import BaseModel

class DescriptionSignature(dspy.Signature):
    field_name = ...
    example = ...
    description = ...

class SyntheticDataGenerator:
    def __init__(
        self, schema_class: Optional[BaseModel] = ..., examples: Optional[List[dspy.Example]] = ...
    ) -> None: ...
    def generate(self, sample_size: int) -> List[dspy.Example]:
        """Generate synthetic examples.

        Args:
            sample_size (int): number of examples to generate
        Raises:
            ValueError: either a schema_class or examples should be provided
        Returns:
            List[dspy.Example]: list of synthetic examples generated
        """
        ...
