"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional, Type
from dspy.adapters.chat_adapter import ChatAdapter, FieldInfoWithName
from dspy.signatures.signature import Signature
from dspy.utils.callback import BaseCallback

class XMLAdapter(ChatAdapter):
    def __init__(self, callbacks: Optional[list[BaseCallback]] = ...) -> None:
        ...
    
    def format_field_with_value(self, fields_with_values: Dict[FieldInfoWithName, Any]) -> str:
        ...
    
    def user_message_output_requirements(self, signature: Type[Signature]) -> str:
        ...
    
    def parse(self, signature: Type[Signature], completion: str) -> dict[str, Any]:
        ...
    


