"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List, Optional
from dspy.clients.provider import Provider, TrainingJob
from dspy.clients.utils_finetune import TrainDataFormat, TrainingStatus

_OPENAI_MODELS = ...
class TrainingJobOpenAI(TrainingJob):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def cancel(self): # -> None:
        ...
    
    def status(self) -> TrainingStatus:
        ...
    


class OpenAIProvider(Provider):
    def __init__(self) -> None:
        ...
    
    @staticmethod
    def is_provider_model(model: str) -> bool:
        ...
    
    @staticmethod
    def finetune(job: TrainingJobOpenAI, model: str, train_data: List[Dict[str, Any]], train_data_format: Optional[TrainDataFormat], train_kwargs: Optional[Dict[str, Any]] = ...) -> str:
        ...
    
    @staticmethod
    def does_job_exist(job_id: str) -> bool:
        ...
    
    @staticmethod
    def does_file_exist(file_id: str) -> bool:
        ...
    
    @staticmethod
    def is_terminal_training_status(status: TrainingStatus) -> bool:
        ...
    
    @staticmethod
    def get_training_status(job_id: str) -> TrainingStatus:
        ...
    
    @staticmethod
    def validate_data_format(data_format: TrainDataFormat): # -> None:
        ...
    
    @staticmethod
    def upload_data(data_path: str) -> str:
        ...
    
    @staticmethod
    def wait_for_job(job: TrainingJobOpenAI, poll_frequency: int = ...): # -> None:
        ...
    
    @staticmethod
    def get_trained_model(job): # -> str | None:
        ...
    


