"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, TypedDict, Union
from dspy.adapters.base import Adapter

class TrainingStatus(str, Enum):
    not_started = ...
    pending = ...
    running = ...
    succeeded = ...
    failed = ...
    cancelled = ...


class TrainDataFormat(str, Enum):
    CHAT = ...
    COMPLETION = ...
    GRPO_CHAT = ...


class Message(TypedDict):
    role: Union[Literal["user"], Literal["assistant"], Literal["system"]]
    content: str
    ...


class MessageAssistant(TypedDict):
    role: Literal["assistant"]
    content: str
    ...


class GRPOChatData(TypedDict):
    messages: List[Message]
    completion: MessageAssistant
    reward: float
    ...


GRPOGroup = List[GRPOChatData]
def infer_data_format(adapter: Adapter) -> str:
    ...

def get_finetune_directory() -> str:
    ...

def write_lines(file_path, data): # -> None:
    ...

def save_data(data: List[Dict[str, Any]]) -> str:
    ...

def validate_data_format(data: List[Dict[str, Any]], data_format: TrainDataFormat): # -> None:
    ...

def find_data_errors_completion(data_dict: Dict[str, str]) -> Optional[str]:
    ...

def find_data_error_chat(messages: Dict[str, Any]) -> Optional[str]:
    ...

def find_data_error_chat_message(message: Dict[str, Any]) -> Optional[str]:
    ...

