"""
This type stub file was generated by pyright.
"""

def default_normalize(s):  # -> str | None:
    ...
def majority(prediction_or_completions, normalize=..., field=...):  # -> Prediction:
    """
    Returns the most common completion for the target field (or the last field) in the signature.
    When normalize returns None, that completion is ignored.
    In case of a tie, earlier completion are prioritized.
    """
    ...
