"""
This type stub file was generated by pyright.
"""

from .predict import Module

class ChainOfThoughtWithHint(Module):
    def __init__(self, signature, rationale_type=..., **config) -> None: ...
    def forward(self, **kwargs): ...
