"""
This type stub file was generated by pyright.
"""

from typing import Optional, Type, Union
from pydantic.fields import FieldInfo
from dspy.primitives.program import Module
from dspy.signatures.field import OutputField
from dspy.signatures.signature import Signature

class ChainOfThought(Module):
    def __init__(
        self,
        signature: Type[Signature],
        rationale_field: Optional[Union[OutputField, FieldInfo]] = ...,
        rationale_field_type: Type = ...,
        **config,
    ) -> None:
        """
        A module that reasons step by step in order to predict the output of a task.

        Args:
            signature (Type[dspy.Signature]): The signature of the module.
            rationale_field (Optional[Union[dspy.OutputField, pydantic.fields.FieldInfo]]): The field that will contain the reasoning.
            rationale_field_type (Type): The type of the rationale field.
            **config: The configuration for the module.
        """
        ...

    def forward(self, **kwargs): ...
    async def aforward(self, **kwargs): ...
