"""
This type stub file was generated by pyright.
"""

from dspy.primitives.program import Module

class MultiChainComparison(Module):
    def __init__(self, signature, M=..., temperature=..., **config) -> None: ...
    def forward(self, completions, **kwargs): ...
