"""
This type stub file was generated by pyright.
"""

from typing import Type, Union
from dspy.primitives.program import Module
from dspy.signatures.signature import Signature

logger = ...

class ProgramOfThought(Module):
    """
    A DSPy module that runs Python programs to solve a problem.
    This module reuires deno to be installed. Please install deno following https://docs.deno.com/runtime/getting_started/installation/

    Example:
    ```
    import dspy

    lm = dspy.LM('openai/gpt-4o-mini')
    dspy.configure(lm=lm)
    pot = dspy.ProgramOfThought("question -> answer")
    pot(question="what is 1+1?")
    ```
    """
    def __init__(self, signature: Union[str, Type[Signature]], max_iters=...) -> None:
        """
        Args:
            signature: The signature of the module.
            max_iters: The maximum number of iterations to retry code generation and execution.
        """
        ...

    def forward(self, **kwargs): ...
