"""
This type stub file was generated by pyright.
"""

from typing import Callable
from dspy.primitives.program import Module

logger = ...

class ReAct(Module):
    def __init__(self, signature, tools: list[Callable], max_iters=...) -> None:
        """
        `tools` is either a list of functions, callable classes, or `dspy.Tool` instances.
        """
        ...

    def forward(self, **input_args):  # -> Prediction:
        ...
    async def aforward(self, **input_args):  # -> Prediction:
        ...
    def truncate_trajectory(self, trajectory):
        """Truncates the trajectory so that it fits in the context window.

        Users can override this method to implement their own truncation logic.
        """
        ...
